package com.company.idm.domain.sync;

public enum ImportConflictCode {
    FILE_DUPLICATE_DEPARTMENT_EXTERNAL_ID,
    FILE_DUPLICATE_DEPARTMENT_CODE,
    FILE_DUPLICATE_USER_ID,
    FILE_DUPLICATE_EMPLOYEE_NO,
    DEPARTMENT_EXTERNAL_ID_CODE_MISMATCH,
    DEPARTMENT_CODE_OWNED_BY_ANOTHER_DEPARTMENT,
    LDAP_GROUP_DN_OCCUPIED,
    USER_ID_EMPLOYEE_NO_MATCH_DIFFERENT_USERS,
    EMPLOYEE_NO_OWNED_BY_ANOTHER_USER,
    LDAP_UID_OCCUPIED,
    OBJECT_VALIDATION_FAILED
}
